### ISSUE TITLE
detailed report still German

### ISSUE THREAD

**Issue by ulno** [Daenara/rhasspy_weather#11]
Sorry for piling up issues here, just to track things correctly (yaeh, sorry I am German too) ;-)

Just to not forget, it would be nice if we could also configure also the detailed report to be in English (or other languages).

**Comment by Daenara** [comment]
already on my todo list (that I typed out a while ago, possibly while you typed this issue). Everything on there is already tracked by me and it might help you figure out what I actually have planned. If we agreed on anything and it is not in there, remind me, I am not 100% sure I got everything.

**Comment by Daenara** [comment]
update: this got fixed a week or two ago
