### ISSUE TITLE
Literal error

### ISSUE THREAD

**Issue by 0synonym** [Daenara/rhasspy_weather#13]
Just a small literal error: on your [Setup for rhasspy hermes app](https://github.com/Daenara/rhasspy_weather/wiki/Setup-for-rhasspy-hermes-app) wiki page you mention `nlu-intent` as parser for rhasspy-hermes-app. I think it should be `nlu_intent` [(Parser)](https://github.com/Daenara/rhasspy_weather/wiki/Parser).

**Comment by Daenara** [comment]
Just fixed that, thanks for catching it.
