### ISSUE TITLE
noon and midnight as time not implemented

### ISSUE THREAD

**Issue by ulno** [Daenara/rhasspy_weather#2]
If asking for the weather tomorrow at midnight, we get:
```
DEBUG:it was a day specified: tomorrow
DEBUG:  named day detected
DEBUG:    named day seems to be an offset from today
DEBUG:it was a time specified: midnight
DEBUG:  named time frame detected: midnight
DEBUG:23:59:00
DEBUG:    named time seems to be a certain time
Traceback (most recent call last):
  File "cli_weather.py", line 70, in <module>
    parse()
  File "cli_weather.py", line 66, in parse
    print(get_weather_forecast(args))
  File "cli_weather.py", line 40, in get_weather_forecast
    request = parse_cli_args(args)
  File "/home/ulno/sync/work/devel/cli_weather/cli_parser/__init__.py", line 105, in parse_cli_args
    new_request.status.set_status(StatusCode.NOT_IMPLEMENTET_ERROR)
  File "/usr/lib/python3.8/enum.py", line 341, in __getattr__
    raise AttributeError(name) from None
AttributeError: NOT_IMPLEMENTET_ERROR
```

How hard is it to implement this?

Also, it would probably be nice to replace IMPLEMENTET with IMPLEMENTED ,- happy to do that myself and do pull request.

**Comment by Daenara** [comment]
Propably not very hard. I just did not get around to that. Also I will fix the typo, just needed an actual IDE for that and not a file opened in browser. There might be more typos in there, or mixups or whatever, seing as English isn't my first language and most code was written when I was half asleep

**Comment by Daenara** [comment]
de8ad46a9c8614d51d5fe563f3500345ac041301
db374b56e6a392115825eec033e14393cf395e5e

That should fix it. The implementation was basically 2 lines and it already worked if you asked for a specific time "12 00" via rhasspy intent, I was just to tired to think about it when I was adding the named times in so I put that there to prevent errors
