### ISSUE TITLE
using capitalize in item discovery in rhasspy_intent prevents languages with small nouns including English

### ISSUE THREAD

**Issue by ulno** [Daenara/rhasspy_weather#7]
Currently in line 139 in rhasspy_intent.py

Can't it use lower here too and lower also the dictionary it compares with?

**Comment by Daenara** [comment]
It can, that part of the code precedes the existence of that list and I overlooked changing it later. I will fix it

**Comment by Daenara** [comment]
Fixed in 6a00fd5198735f93fbdb10f94e86478eb2b5f5a2
